// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHcT7EXRLH_lyPnovSZvYcIOdWSCwO-N8',
    appId: '1:516187552464:web:e1a89cb50436b729bf7cd5',
    messagingSenderId: '516187552464',
    projectId: 'airport-app-20516',
    authDomain: 'airport-app-20516.firebaseapp.com',
    storageBucket: 'airport-app-20516.firebasestorage.app',
    measurementId: 'G-0QTE994XBK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxfD-Ef-bA_wl_-bElqmKRxdBZ-DPB46g',
    appId: '1:516187552464:android:f88003ebc1553364bf7cd5',
    messagingSenderId: '516187552464',
    projectId: 'airport-app-20516',
    storageBucket: 'airport-app-20516.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQFLtk1M7wYVknkp0zrKTLcnmYoFglVko',
    appId: '1:516187552464:ios:f436913a75f8d092bf7cd5',
    messagingSenderId: '516187552464',
    projectId: 'airport-app-20516',
    storageBucket: 'airport-app-20516.firebasestorage.app',
    iosBundleId: 'com.mustafa.airportApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHcT7EXRLH_lyPnovSZvYcIOdWSCwO-N8',
    appId: '1:516187552464:web:ed96ad434a3d261abf7cd5',
    messagingSenderId: '516187552464',
    projectId: 'airport-app-20516',
    authDomain: 'airport-app-20516.firebaseapp.com',
    storageBucket: 'airport-app-20516.firebasestorage.app',
    measurementId: 'G-MYDXL1B1GZ',
  );
}
